# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_data.proto',
  package='ParrotAR2DroneSensorData',
  serialized_pb=_b('\n\x11sensor_data.proto\x12\x18ParrotAR2DroneSensorData\"\x9d\x02\n\nSensorData\x12\x11\n\tunix_time\x18\x01 \x01(\x03\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\x05\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x05\x12\r\n\x05pitch\x18\x04 \x01(\x05\x12\x0c\n\x04roll\x18\x05 \x01(\x05\x12\x0b\n\x03yaw\x18\x06 \x01(\x05\x12\n\n\x02vx\x18\x07 \x01(\x01\x12\n\n\x02vy\x18\x08 \x01(\x01\x12\n\n\x02vz\x18\t \x01(\x01\x12\x0b\n\x03\x66ly\x18\n \x01(\x05\x12>\n\x06images\x18\x0b \x03(\x0b\x32..ParrotAR2DroneSensorData.SensorData.ImageData\x1a>\n\tImageData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSORDATA_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='ParrotAR2DroneSensorData.SensorData.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ParrotAR2DroneSensorData.SensorData.ImageData.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='ParrotAR2DroneSensorData.SensorData.ImageData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='ParrotAR2DroneSensorData.SensorData.ImageData.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=333,
)

_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='ParrotAR2DroneSensorData.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unix_time', full_name='ParrotAR2DroneSensorData.SensorData.unix_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery', full_name='ParrotAR2DroneSensorData.SensorData.battery', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ParrotAR2DroneSensorData.SensorData.altitude', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='ParrotAR2DroneSensorData.SensorData.pitch', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll', full_name='ParrotAR2DroneSensorData.SensorData.roll', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='ParrotAR2DroneSensorData.SensorData.yaw', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vx', full_name='ParrotAR2DroneSensorData.SensorData.vx', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vy', full_name='ParrotAR2DroneSensorData.SensorData.vy', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vz', full_name='ParrotAR2DroneSensorData.SensorData.vz', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fly', full_name='ParrotAR2DroneSensorData.SensorData.fly', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='images', full_name='ParrotAR2DroneSensorData.SensorData.images', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SENSORDATA_IMAGEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=333,
)

_SENSORDATA_IMAGEDATA.containing_type = _SENSORDATA
_SENSORDATA.fields_by_name['images'].message_type = _SENSORDATA_IMAGEDATA
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), dict(

  ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), dict(
    DESCRIPTOR = _SENSORDATA_IMAGEDATA,
    __module__ = 'sensor_data_pb2'
    # @@protoc_insertion_point(class_scope:ParrotAR2DroneSensorData.SensorData.ImageData)
    ))
  ,
  DESCRIPTOR = _SENSORDATA,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:ParrotAR2DroneSensorData.SensorData)
  ))
_sym_db.RegisterMessage(SensorData)
_sym_db.RegisterMessage(SensorData.ImageData)


# @@protoc_insertion_point(module_scope)
